Inaugural blog post
nivenly/website pull request #11
Opened 2023-03-02 03:32 UTC by quintessence

2023-03-02 04:21 UTC, krisnova requested changes

2023-03-03 23:07 UTC, quintessence commented
@krisnova please review the "Why a non-profit", "What's governance and legal support", and "what's next" sections in particular.

2023-03-04 05:53 UTC, krisnova commented on content/en/blog/2023/2023-03-01-first-post.md
> +1. Makes it easier to partner with other entities, both for-profit and non-profit.
```suggestion
2. Makes it easier to partner with other entities, both for-profit and non-profit.
```

2023-03-05 03:19 UTC, quintessence commented on content/en/blog/2023/2023-03-01-first-post.md
> +General memberships are currently $7 / mo. (USD) and are available on [our Open Collective page](https://opencollective.com/nivenly-foundation).
I wouldn't mention this until we are in a position to know what we're going to do for it.

2023-03-05 03:27 UTC, krisnova approved these changes

2023-03-05 03:45 UTC, merged